service: serverless-graphql-client

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-3

plugins:
  - serverless-finch

custom:
  client:
    bucketName: cuistotducoin-front
    distributionFolder: build