service: serverless-ssr

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-stage-manager

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  stages:
    - development
    - staging
    - production
  dotenv:
    path: .env
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${env:AWS_DOMAIN}
    createRoute53Record: true
    certificateName: ${env:AWS_DOMAIN}

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ${env:AWS_REGION_PARIS}
  deploymentBucket: ${env:AWS_S3_BUCKET}
  endpointType: regional

package:
  exclude:
    - ./**
  include:
    - build/**

functions:
  ssr:
    timeout: 30
    handler: build/lambda.handler
    events:
      - http:
          method: any
          cors: true
          path: /
      - http:
          method: any
          path: /{any+}
          cors: true