service: serverless-ssr

plugins:
  - serverless-dotenv-plugin

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  dotenv:
    path: .env

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${env:AWS_REGION_PARIS}
  deploymentBucket: ${env:AWS_S3_BUCKET}

package:
  exclude:
    - ./**
  include:
    - build/**

functions:
  ssr:
    timeout: 30
    handler: build/server
    events:
      - http:
          method: get
          path: /