service: serverless-ssr

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-sentry
  - serverless-stage-manager

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  stages:
    - development
    - staging
    - production
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:provider.environment.AWS_DOMAIN}
    createRoute53Record: true
    certificateName: ${self:provider.environment.AWS_DOMAIN}
  sentry:
    dsn: ${self:provider.environment.SENTRY_DSN}
    organization: cuistotducoin
    project: front

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'development'}
  region: eu-west-1
  deploymentBucket: ${self:provider.environment.AWS_DEPLOYMENT_BUCKET}
  endpointType: regional


package:
  exclude:
    - ./**
  include:
    - build/**

functions:
  ssr:
    timeout: 30
    handler: build/lambda.handler
    events:
      - http:
          method: any
          path: /
      - http:
          method: any
          path: /{any+}