service: serverless-ssr

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-sentry
  - serverless-stage-manager

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  stages:
    - development
    - staging
    - production
  apigwBinary:
    types:
      - '*/*'
  sentry:
    dsn: ${self:provider.environment.SENTRY_DSN}
    organization: cuistotducoin
    project: front

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'development'}
  region: eu-west-1
  deploymentBucket: front-ssr-production
  endpointType: regional
  environment:
    AWS_DOMAIN: ${ssm:/cuistot/front/domain~true}
    AWS_REGION_IRELAND: eu-west-1
    AWS_DEPLOYMENT_BUCKET: front-ssr-production
    AWS_USERPOOL_ID: ${ssm:/cuistot/userpool-id~true}
    AWS_IDENTITY_POOL_ID: ${ssm:/cuistot/identity-pool-id~true}
    AWS_STORE_BUCKET: ${ssm:/cuistot/store-bucket~true}
    AWS_APP_CLIENT_ID: ${ssm:/cuistot/app-client-id~true}
    GRAPHQL_API_URL: ${ssm:/cuistot/front/graphql-api-url~true}
    GUEST_USERNAME: ${ssm:/cuistot/front/guest-username~true}
    GUEST_PASSWORD: ${ssm:/cuistot/front/guest-password~true}
    ALGOLIASEARCH_SEARCH_APP_ID: ${ssm:/cuistot/front/algolia-search-app-id~true}
    ALGOLIASEARCH_SEARCH_KEY: ${ssm:/cuistot/front/algolia-search-key~true}
    ALGOLIASEARCH_PLACES_APP_ID: ${ssm:/cuistot/front/algolia-places-app-id~true}
    ALGOLIASEARCH_PLACES_KEY: ${ssm:/cuistot/front/algolia-places-key~true}
    SENTRY_DSN: ${ssm:/cuistot/front/sentry-dsn~true}
    EXECUTION_ENV: lambda
    NODE_ENV: ${opt:stage,'development'}

package:
  exclude:
    - ./**
  include:
    - build/**

functions:
  ssr:
    timeout: 30
    handler: build/server.handler
    events:
      - http:
          method: get
          path: /
          cors: true
      - http:
          method: any
          path: /{proxy+}
          cors: true