extends: airbnb-base
overrides:
  - files: ["*.js"]
    rules:
      no-plusplus: "off"
      newline-per-chained-call:
        - error
        - ignoreChainWithDepth: 3
      import/prefer-default-export: "off"
      no-console: "off"
      object-curly-newline:
        - error
        - ExportDeclaration:
            multiline: true
            minProperties: 5
          ImportDeclaration:
            multiline: true
            minProperties: 5
          ObjectExpression:
            multiline: true
          ObjectPattern:
            multiline: true
      prefer-destructuring: "off"
