service: cuistot-service

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:NODE_ENV}
  region: ${env:AWS_REGION_IRELAND}
  profile: default

plugins:
  - serverless-appsync-plugin
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
    packager: 'yarn' # Packager that will be used to package your external modules
  dotenv:
    path: .env
  accountId: ${env:AWS_ACCOUNT_ID}
  appSync:
    name: cuistot-appsync-${self:provider.stage}
    authenticationType: API_KEY
    userPoolConfig:
      awsRegion: ${env:AWS_REGION_LONDON}
      defaultAction: ALLOW
      userPoolId: ${env:AWS_USERPOOL_ID}
    region: ${env:AWS_REGION_IRELAND}
    mappingTemplates:
      # Mutation mapping templates
      - dataSource: Lambda
        type: Mutation
        field: createWorkshop
        request: "workshop/createWorkshop-request-mapping-template.txt"
        response: "workshop/createWorkshop-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateWorkshop
        request: "workshop/updateWorkshop-request-mapping-template.txt"
        response: "workshop/updateWorkshop-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: deleteWorkshop
        request: "workshop/deleteWorkshop-request-mapping-template.txt"
        response: "workshop/deleteWorkshop-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: addWorkshopImage
        request: "workshop/addWorkshopImage-request-mapping-template.txt"
        response: "workshop/addWorkshopImage-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: removeWorkshopImage
        request: "workshop/removeWorkshopImage-request-mapping-template.txt"
        response: "workshop/removeWorkshopImage-response-mapping-template.txt"

      - dataSource: Lambda
        type: Mutation
        field: createBooking
        request: "booking/createBooking-request-mapping-template.txt"
        response: "booking/createBooking-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateBooking
        request: "booking/updateBooking-request-mapping-template.txt"
        response: "booking/updateBooking-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: deleteBooking
        request: "booking/deleteBooking-request-mapping-template.txt"
        response: "booking/deleteBooking-response-mapping-template.txt"

      - dataSource: Lambda
        type: Mutation
        field: createEvaluation
        request: "evaluation/createEvaluation-request-mapping-template.txt"
        response: "evaluation/createEvaluation-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: deleteEvaluation
        request: "evaluation/deleteEvaluation-request-mapping-template.txt"
        response: "evaluation/deleteEvaluation-response-mapping-template.txt"

      - dataSource: Lambda
        type: Mutation
        field: createGourmet
        request: "gourmet/createGourmet-request-mapping-template.txt"
        response: "gourmet/createGourmet-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateGourmet
        request: "gourmet/updateGourmet-request-mapping-template.txt"
        response: "gourmet/updateGourmet-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: deleteGourmet
        request: "gourmet/deleteGourmet-request-mapping-template.txt"
        response: "gourmet/deleteGourmet-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateGourmetImage
        request: "gourmet/updateGourmetImage-request-mapping-template.txt"
        response: "gourmet/updateGourmetImage-response-mapping-template.txt"

      - dataSource: Lambda
        type: Mutation
        field: createCook
        request: "cook/createCook-request-mapping-template.txt"
        response: "cook/createCook-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateCook
        request: "cook/updateCook-request-mapping-template.txt"
        response: "cook/updateCook-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: deleteCook
        request: "cook/deleteCook-request-mapping-template.txt"
        response: "cook/deleteCook-response-mapping-template.txt"

      - dataSource: Lambda
        type: Mutation
        field: createKitchen
        request: "kitchen/createKitchen-request-mapping-template.txt"
        response: "kitchen/createKitchen-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateKitchen
        request: "kitchen/updateKitchen-request-mapping-template.txt"
        response: "kitchen/updateKitchen-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: deleteKitchen
        request: "kitchen/deleteKitchen-request-mapping-template.txt"
        response: "kitchen/deleteKitchen-response-mapping-template.txt"

      # Query mapping templates
      - dataSource: Lambda
        type: Query
        field: getWorkshop
        request: "workshop/getWorkshop-request-mapping-template.txt"
        response: "workshop/getWorkshop-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getWorkshops
        request: "workshop/getWorkshops-request-mapping-template.txt"
        response: "workshop/getWorkshops-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getGourmet
        request: "gourmet/getGourmet-request-mapping-template.txt"
        response: "gourmet/getGourmet-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getCook
        request: "cook/getCook-request-mapping-template.txt"
        response: "cook/getCook-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getKitchen
        request: "kitchen/getKitchen-request-mapping-template.txt"
        response: "kitchen/getKitchen-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getBooking
        request: "booking/getBooking-request-mapping-template.txt"
        response: "booking/getBooking-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getEvaluation
        request: "evaluation/getEvaluation-request-mapping-template.txt"
        response: "evaluation/getEvaluation-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: getCurrentGourmet
        request: "getCurrentGourmet-request-mapping-template.txt"
        response: "getCurrentGourmet-response-mapping-template.txt"

      # Nested fields
      - dataSource: Lambda
        type: Cook
        field: gourmet
        request: "cook/cookGourmet-request-mapping-template.txt"
        response: "cook/cookGourmet-response-mapping-template.txt"
      - dataSource: Lambda
        type: Workshop
        field: kitchen
        request: "workshop/workshopKitchen-request-mapping-template.txt"
        response: "workshop/workshopKitchen-response-mapping-template.txt"
      - dataSource: Lambda
        type: Workshop
        field: cook
        request: "workshop/workshopCook-request-mapping-template.txt"
        response: "workshop/workshopCook-response-mapping-template.txt"
      - dataSource: Lambda
        type: Workshop
        field: bookings
        request: "workshop/workshopBookings-request-mapping-template.txt"
        response: "workshop/workshopBookings-response-mapping-template.txt"
      - dataSource: Lambda
        type: Booking
        field: gourmet
        request: "booking/bookingGourmet-request-mapping-template.txt"
        response: "booking/bookingGourmet-response-mapping-template.txt"
      - dataSource: Lambda
        type: Booking
        field: workshop
        request: "booking/bookingWorkshop-request-mapping-template.txt"
        response: "booking/bookingWorkshop-response-mapping-template.txt"
      - dataSource: Lambda
        type: Booking
        field: evaluation
        request: "booking/bookingEvaluation-request-mapping-template.txt"
        response: "booking/bookingEvaluation-response-mapping-template.txt"
      - dataSource: Lambda
        type: Evaluation
        field: booking
        request: "evaluation/evaluationBooking-request-mapping-template.txt"
        response: "evaluation/evaluationBooking-response-mapping-template.txt"
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AWS_LAMBDA
        name: Lambda
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: "arn:aws:lambda:${self:custom.appSync.region}:${self:custom.accountId}:function:${self:service}-${self:provider.stage}-graphql"
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Lambda-${self:custom.appSync.serviceRole}-${self:provider.stage}"

functions:
  graphql:
    handler: handler.graphqlHandler

resources:
  Resources:
    DBInstance:
      Type: "AWS::RDS::DBInstance"
      DeletionPolicy: "Retain"
      Properties:
        DBInstanceIdentifier: "cuistot-postgres-${self:provider.stage}"
        DBName: "cuistot_${self:provider.stage}"
        AllocatedStorage: "20"
        DBInstanceClass: "db.t2.micro"
        Engine: "postgres"
        EngineVersion: "9.6.6"
        MasterUsername: ${env:DATABASE_USERNAME}
        MasterUserPassword: ${env:DATABASE_PASSWORD}
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      DeletionPolicy : "Delete"
      Properties:
        RoleName: "Lambda-${self:custom.appSync.serviceRole}-${self:provider.stage}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Lambda-${self:custom.appSync.serviceRole}-${self:provider.stage}-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "arn:aws:lambda:${self:custom.appSync.region}:*:function:${self:service}-${self:provider.stage}-graphql"
                    - "arn:aws:lambda:${self:custom.appSync.region}:*:function:${self:service}-${self:provider.stage}-graphql:*"
