version: 2
jobs:
  deploy-admin:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "admin/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd admin
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "admin/yarn.lock" }}
          paths:
            - ./node_modules
      - run: &install_awscli
          name: Install awscli
          working_directory: /
          command: |
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python2.7 get-pip.py
            sudo apt-get update
            sudo apt-get install python-pip libpython-dev groff
            sudo pip install awscli
      - run:
          name: Build admin
          command: |
            cd admin
            yarn build
      - run:
          name: Deploy admin to S3
          command: |
            cd admin
            yarn deploy-build
  
  deploy-front-prod:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache: &restore_front_cache
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
      - run: &install_front_dependencies
          name: Install dependencies
          command: |
            cd frontend
            sudo npm i -g serverless
            yarn install
      - save_cache: &save_front_cache
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn build:prod
      - run:
          name: Deploy frontend
          command: |
            cd frontend
            yarn deploy:prod

  deploy-back-prod:
    docker:
      - image: circleci/node:8.10
    environment:
      GOPATH: /home/circleci/go
      AWS_CONFIG_FILE: /home/circleci/.aws/config # need to be explicitly exported
      AWS_CONFIG_PATH: /home/circleci/.aws
    steps:
      - checkout
      - restore_cache: &restore_back_cache
          key: dependency-cache-{{ checksum "backend/yarn.lock" }}
      # - run: *install_awscli
      # - run: &install_go
      #     name: Install go
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get -y upgrade
      #       wget https://dl.google.com/go/go1.6.4.linux-amd64.tar.gz
      #       sudo tar -xf go1.6.4.linux-amd64.tar.gz
      #       sudo mv go /usr/local
      #       mkdir $GOPATH
      #       echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV
      #       source $BASH_ENV
      #       go get -u github.com/remind101/assume-role
      - run: &build_aws_profiles
          name: Build AWS config
          command: |
            sudo mkdir $AWS_CONFIG_PATH
            sudo AWS_CONFIG_PATH=$AWS_CONFIG_PATH AWS_CROSS_ACCOUNT_ID=$AWS_CROSS_ACCOUNT_ID STAGE=$STAGE AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY node build_aws_profile
            ls -l /home/circleci/.aws
      - run: &install_back_dependencies
          name: Install dependencies
          command: |
            cd backend
            sudo npm i -g serverless
            yarn install --production=false
      - save_cache: &save_back_cache
          key: dependency-cache-{{ checksum "backend/yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Deploy backend
          command: |
            cd backend
            sudo cat $AWS_CONFIG_PATH/credentials
            sudo cat $AWS_CONFIG_PATH/config
            assume-role production
            # yarn deploy:prod

  deploy-front-stage:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache: *restore_front_cache
      - run: *install_front_dependencies
      - save_cache: *save_front_cache
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn build:stage
      - run:
          name: Deploy frontend
          command: |
            cd frontend
            yarn deploy:stage

  deploy-back-stage:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache: *restore_back_cache
      - run: *install_back_dependencies
      - save_cache: *save_back_cache
      - run:
          name: Deploy backend
          command: |
            cd backend
            yarn deploy:stage

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-admin:
          filters:
            branches:
              only:
                - master
      - deploy-front-prod:
          filters:
            branches:
              only:
                - master
      - deploy-back-prod:
          context: production
          filters:
            branches:
              only:
                - feature/setup_deployment # to remove
                - master
      - deploy-front-stage:
          filters:
            branches:
              only:
                - release/*
      - deploy-back-stage:
          filters:
            branches:
              only:
                - release/*
