version: 2
jobs:
  deploy-admin:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "admin/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd admin
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "admin/yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install awscli
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: Build admin
          command: |
            cd admin
            yarn build
      - run:
          name: Deploy admin to S3
          command: |
            cd admin
            yarn deploy-build
  
  deploy-front:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd frontend
            sudo npm i -g serverless
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn build
      - run:
          name: Deploy frontend
          command: |
            cd frontend
            yarn deploy


workflows:
  version: 2
  deploy:
    jobs:
      - deploy-admin:
          filters:
            branches:
              only:
                - master
                - feature/setup_deployment # to remove
      - deploy-front:
          filters:
            branches:
              only:
                - master