version: 2
jobs:
  deploy-admin:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "admin/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd admin
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "admin/yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install awscli
          working_directory: /
          command: |
            sudo apt-get install python3.4-dev python3-setuptools
            sudo easy_install3 pip
            pip3 install awscli --upgrade --user
            export PATH=/usr/bin/python3/bin:$PATH
      - run:
          name: Build admin
          command: |
            cd admin
            yarn build
      - run:
          name: Deploy admin to S3
          command: |
            cd admin
            yarn deploy-build
  
  deploy-front:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd frontend
            sudo npm i -g serverless
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn build
      - run:
          name: Deploy frontend
          command: |
            cd frontend
            yarn deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-admin:
          filters:
            branches:
              only:
                - master
                - feature/setup_deployment # to remove
      - deploy-front:
          filters:
            branches:
              only:
                - master