version: 2
jobs:
  # test:
  #   docker:
  #     - image: circleci/node:8.10

  #   working_directory: ~/cuistot-test

  #   steps:
  #     - checkout

  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}

  #     - run:
  #         name: Install dependencies
  #         command: yarn install

  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #         paths:
  #           - ./node_modules

  #     - run: 
  #         name: Run tests with coverage
  #         command: |
  #           cd cuistot/admin
  #           yarn test --coverage

  deploy:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/cuistot-deploy

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: |
            yarn install
            sudo apt-get install awscli

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      
      - run:
          name: Build application
          command: |
            cd cuistot/admin
            yarn build

      - run:
          name: Deploy application to S3
          command: yarn deploy-build

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy
      # - test
      # - deploy:
          # requires:
            # - test