extends: airbnb
overrides:
  - files: ["*.js"]
    rules:
      max-len:
        - "error"
        - code: 300
      react/jsx-filename-extension:
        - 1
        - extensions:
          - ".js"
          - ".jsx"
      react/require-default-props: 0
      react/forbid-prop-types: 0
      react/destructuring-assignment: 0
      react/jsx-one-expression-per-line: 0
      react/prop-types: 0
      react/no-array-index-key: 0
      no-console: 0
